#!/bin/bash
set -e

. $(dirname $0)/build-common

docker run --rm -v `pwd`:/go/src/github.com/docker/libcompose docker-compose gox "${OS_PLATFORM_ARG[@]}" "${OS_ARCH_ARG[@]}" -output="docker-compose_{{.OS}}-{{.Arch}}" -ldflags="-w -X github.com/docker/libcompose/version.GITCOMMIT `git rev-parse --short HEAD`" ./cli/main
